name: .NET

on:
  push:
    branches: [ dna-tls-patch ]
  pull_request:
    branches: [ dna-tls-patch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Npgsql
    - name: Build
      run: dotnet build Npgsql --no-restore
    - name: Test
      run: dotnet test Npgsql --no-build --verbosity normal
