name: .NET

on:
  push:
    branches: [ dna-tls-patch ]
  pull_request:
    branches: [ dna-tls-patch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore Npgsql.sln
    - name: Build
      run: dotnet build Npgsql.sln --no-restore -c ReleaseOptimizedCryptography /p:Platform=x86
# tests are currently disabled as they will require postgres to be installed
# and running. Not that hard but probably not needed as our changes are minimal
    #- name: Test
    #  run: dotnet test Npgsql.sln --no-build --verbosity normal
